package com.practice5.demo.controller;
import com.practice5.demo.domain.Person;
import com.practice5.demo.domain.Phone;
import com.practice5.demo.repository.PersonRepository;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController// This means that this class is a Controller
    @RequestMapping(path="/persons") // This means URL's start with /persons (after Application path)
    public class MainController {
        @Autowired // This means to get the bean called userRepository
                   // Which is auto-generated by Spring, we will use it to handle the data
        private PersonRepository personRepository;

        @PostMapping(path="/add") // Map ONLY POST Requests
        public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam Integer age ,@RequestParam Phone phone) {
            // @ResponseBody means the returned String is the response, not a view name
            // @RequestParam means it is a parameter from the GET or POST request
            Person n = new Person();
            n.setName(name);
            n.setAge(age);
            n.setPhone(phone);
            personRepository.save(n);
            return "Saved";
        }
        @GetMapping(path="/all")
        public @ResponseBody Iterable<Person> getAllUsers() {
            // This returns a JSON or XML with the users
            return personRepository.findAll();
        }
    @GetMapping(path="/alls")
    public @ResponseBody Iterable<Person> getAllUserss() {
        // This returns a JSON or XML with the users
        List<Person> personList=personRepository.findByAgeLessThan(20);
        return personList;
    }

    }











